config/routes.rb
FoodrecoServer::Application.routes.draw do
  
  resource :landing,  :only  => [:show]
  resource :session,  :only  => [:create, :destroy]
  resources :surveys, :only  => [:new, :update, :edit] do
  resources :meals, :except => [:show]
  end

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "Landings#show"

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected :id
  belongs_to :survey
  belongs_to :user

  Meal::DAYS        = %W[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  Meal::HOURS       = (1..24).to_a
  Meal::PLACES      = ["Bakery/Dessert", "Beer", "Bistro/Brasserie", "Cafe", "Catering", "Cha Chaan Teng", "Coffee Shop", "Dance Clubs", "Deli", "Delivery", "Fast Food", "Karaoke", "Kiosk/Stall", "Lounge", "Pub/Bar", "Restaurant", "Tea", "Wine/Spirits"].sort
   Meal::CUISINES   = {"African" => "African".split(","), "Asian"=> "Chinese,Indian,Cambodian,Thai,Vietnamese,Japanese,Korean,Malay,Nepalese,Nonya,Philippine,Singaporean".split(","), "Argentinean" => "Argentinean".split(","), "Brazilian" => "Brazilian".split(","), "Caribbean" => "Caribbean".split(","), "Mexican" => "Mexican".split(","), "Lebanese" => "Lebanese".split(","),"Persian" => "Persian".split(","), "Turkish" => "Pizza,Seafood,Steak and Grills,Steamboat,Vegetarian".split(","),  "American" => "American".split(","), "Australian" => "Australian".split(","), "Canadian" => "Canadian".split(","),"European" => "Belgian, Czech, Danish, Dutch, English, French, German, Greek, Irish, Italian, Portuguese, Russian, Spanish, Swedish, Swiss".split(","), "Mediterranean" => "Mediterranean".split(","), "New Zealand" => "New Zealand".split(",")}

  #Meal::CUISINES    = {:lol => ["12","3","4"], :engrasos => ["LOOOL"]}
  Meal::PRICES      = ["S$1-S$15", "S$16-S$30", "S$31-S$45", "S$46-S$60", "S$60 and more"]
  Meal::RECOMMENDED = ["After Work", "Alfresco/Outdoor", " ining", "Beer Lists", "Boys Night Out", "Breakfast", "Brunch", "Buffet", "Business Breakfast", "Business Dining", "Cheap Eat/Budget", "Children/Family", "Chillout", "Corporate Functions", "Dancing", "Dinner", "Fine Dining", "Girls Night Out", "Healthy Eating", "Hi Tea", "Hidden FindLarge Group", "Live Music", "Lunch", "People Watching", "Pet Friendly", "Private Dining", "Quiet/Peaceful", "Romance/First Dates", "Supper/Night Dining", "Take Away", "Vegetarians", "Vibrant/Noisy", "View/Scenery", "Waterfront", "Weddings", "Wheelchair Friendly", "Wine Lists"].sort

  validates :day,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false,
            :inclusion => { :in => Meal::DAYS }
            # ,
            # :uniqueness => { :scope => :user_id,
            #                 :message => "You've already picked %{value}" }

  validates :hour,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false,
            :inclusion => { :in => Meal::HOURS }
            # ,
            # :uniqueness => { :scope => [:user_id, :day],
            #                 :message => "You've already picked %{value} on that day" }


  validates :place,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false,
            :inclusion => { :in => Meal::PLACES }


  validates :cuisine,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false
            #,:inclusion => { :in => Meal::CUISINES }

  validates :price,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false,
            :inclusion => { :in => Meal::PRICES }

  validates :recommended,
            :presence => true,
            :allow_nil => false,
            :allow_blank => false,
            :inclusion => { :in => Meal::RECOMMENDED }



end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
   @meals = current_user.survey.meals
  end

  def new
    @survey = current_user.survey
    @meal  = @survey.meals.build
  end

  def create
    @survey = current_user.survey
    @meal = @survey.meals.build params[:meal]
    if @meal.save
      redirect_to survey_meals_path(@survey)
    else
      render :new
    end
  end

  def edit
    @survey = current_user.survey
    @meal  = @survey.meals.find params[:id]
  end

  def update
    @survey = current_user.survey
    @meal = @survey.meals.find params[:id] 
    if @meal.update_attributes params[:meal]
      redirect_to survey_meals_path(@survey)
    else
      render :new
    end
  end

  def destroy
    @survey = current_user.survey
    @meal = @survey.meals.find params[:id]
    @meal.destroy
    redirect_to survey_meals_path @survey
  end

end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.haml
= simple_form_for [survey, meal] do |f|
  = f.input :day,         :collection => Meal::DAYS
  = f.input :hour,        :collection => Meal::HOURS
  = f.input :place,       :collection => Meal::PLACES
  = f.input :cuisine,     :collection => Meal::CUISINES, :as => :grouped_select, :group_method => :last
  = f.input :price,       :collection => Meal::PRICES
  = f.input :recommended, :collection => Meal::RECOMMENDED

  = f.button :submit 

app/views/meals/_meal.html.haml
%p 
  You ate on
  %span= meal.day
  , around the hours 
  %span= meal.hour
  at a 
  %span= meal.place
  eating 
  %span= meal.cuisine
  that was 
  %span= meal.recommended
  for around
  %span= meal.price

=link_to "Edit",    edit_survey_meal_path(meal.survey, meal)
=button_to "Delete", survey_meal_path(meal.survey, meal), :confirm => "Are you sure you want to delete this?", :method => :delete

app/views/meals/edit.html.haml
=render :partial => "form", :locals => {:survey => @survey, :meal => @meal}

app/views/meals/index.html.haml
-if @meals.blank?
  .well
    %p You probably should add a couple of meals :-)
- for meal in @meals
  = render meal

app/views/meals/new.html.haml
=render :partial => "form", :locals => {:survey => @survey, :meal => @meal}